# ---- Explicit project build information ---- #
[tool.ruff]
line-length = 88
# Adopt from pytorch/.flake8. Change if needed.
lint.ignore = [
    "E203", "E305", "E402", "E501", "E721", "E741", "F405", "F821", "F841",
    "C408", "E302", "W291", "E303", "N812", "N817", "E731", "N803", "N806"
]
